use_frameworks!

platform :ios, '8.0'

target 'KochavaLocationiOS_Example' do
  # pod 'KochavaTrackeriOS'
  pod 'KochavaLocationiOS', :path => '../'

  target 'KochavaLocationiOS_Tests' do
    inherit! :search_paths

    
  end
end
