use_frameworks!

target 'KochavaLocationiOS_Example' do
  pod 'KochavaTrackeriOS'
  pod 'KochavaLocationiOS', :path => '../'

  target 'KochavaLocationiOS_Tests' do
    inherit! :search_paths

    
  end
end
